# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
print ('resultados arredondados para 2 casas deciamis')
a = 3.0/5.0 + 2
print ('a =',a)
b = (a + 10.2) - (5.0*2.0)
b = round(b,1)
print ('b =',b)
c = (a/b)+ 33.8
print ('c =',round(c,2))
d = (a/(b+c))
print ('d =',round(d,2))
e = d*2
print ('e =',round(e,2))

resultados arredondados para 2 casas deciamis
a = 2.6
b = 2.8
c = 34.73
d = 0.07
e = 0.14

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [2]:
a2 = [2.0,3.0,5.0] + [10, 20, 30]
print('a =',a2)
b2 = a2 * 2
print('b =',b2)
c2 = a2 + b2
print('c =',c2)

try:
    d2 = a2/(b2*c2)
    print('d =',d2)
except Exception as d2:
    print(d2)

a = [2.0, 3.0, 5.0, 10, 20, 30]
b = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
c = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [3]:
lista_1 = [a, b, c, d, e]
lista_2 = [a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista_3 = lista_1 + lista_2
lista_3 = [round(n, 4) for n in lista_3]
lista_3

[2.6, 2.8, 34.7286, 0.0693, 0.1386, 1.6125, 1.6733, 5.8931, 0.2632, 0.3722]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [4]:
import numpy as np
import pandas as pd

lista_3 += lista_3
array_3 = np.array(lista_3)
array_4 = array_3.reshape((5,4))
print(array_4)

[[ 2.6     2.8    34.7286  0.0693]
 [ 0.1386  1.6125  1.6733  5.8931]
 [ 0.2632  0.3722  2.6     2.8   ]
 [34.7286  0.0693  0.1386  1.6125]
 [ 1.6733  5.8931  0.2632  0.3722]]

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [5]:
lista_4 = [np.mean(array_4, axis=0)]
print(lista_4)

[array([7.88074, 2.14942, 7.88074, 2.14942])]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [6]:
shape = array_4.shape
shape
array_5 = np.append(array_4, lista_4, axis=0)
array_5

array([[ 2.6    ,  2.8    , 34.7286 ,  0.0693 ],
       [ 0.1386 ,  1.6125 ,  1.6733 ,  5.8931 ],
       [ 0.2632 ,  0.3722 ,  2.6    ,  2.8    ],
       [34.7286 ,  0.0693 ,  0.1386 ,  1.6125 ],
       [ 1.6733 ,  5.8931 ,  0.2632 ,  0.3722 ],
       [ 7.88074,  2.14942,  7.88074,  2.14942]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [7]:
array_5.reshape(-1,4)
Dataframe_5 = pd.DataFrame(array_5).round(3)
Dataframe_5

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [8]:
media_linha = np.mean(Dataframe_5, axis=1)
Dataframe_5['media_linha'] = media_linha
Dataframe_5

        0      1       2      3  media_linha
0   2.600  2.800  34.729  0.069     10.04950
1   0.139  1.612   1.673  5.893      2.32925
2   0.263  0.372   2.600  2.800      1.50875
3  34.729  0.069   0.139  1.612      9.13725
4   1.673  5.893   0.263  0.372      2.05025
5   7.881  2.149   7.881  2.149      5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [9]:
print("ultima linha -")
print(Dataframe_5.iloc[:-1].describe())
print()
print("ultima coluna -")
print(Dataframe_5.transpose().iloc[:-1].describe())

ultima linha -
               0         1          2         3  media_linha
count   5.000000  5.000000   5.000000  5.000000     5.000000
mean    7.880800  2.149200   7.880800  2.149200     5.015000
std    15.043402  2.356578  15.043402  2.356578     4.202259
min     0.139000  0.069000   0.139000  0.069000     1.508750
25%     0.263000  0.372000   0.263000  0.372000     2.050250
50%     1.673000  1.612000   1.673000  1.612000     2.329250
75%     2.600000  2.800000   2.600000  2.800000     9.137250
max    34.729000  5.893000  34.729000  5.893000    10.049500

ultima coluna -
               0         1         2          3         4         5
count   4.000000  4.000000  4.000000   4.000000  4.000000  4.000000
mean   10.049500  2.329250  1.508750   9.137250  2.050250  5.015000
std    16.499883  2.479423  1.378677  17.075994  2.640696  3.309372
min     0.069000  0.139000  0.263000   0.069000  0.263000  2.149000
25%     1.967250  1.243750  0.344750   0.121500  0.344750  2.149000
50%     2.700000  1.642500  1.486000   0.875500  1.022500  5.015000
75%    10.782250  2.728000  2.650000   9.891250  2.728000  7.881000
max    34.729000  5.893000  2.800000  34.729000  5.893000  7.881000

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
print("ultima linha -")
print(Dataframe_5.iloc[:-1].rename(columns={'media_linha':'media_da_media_linha'}).describe())
print()
print("ultima coluna -")
print(Dataframe_5.transpose().iloc[:-1].rename(columns={5:'media_da_media'}).describe())

ultima linha -
               0         1          2         3  media_da_media_linha
count   5.000000  5.000000   5.000000  5.000000              5.000000
mean    7.880800  2.149200   7.880800  2.149200              5.015000
std    15.043402  2.356578  15.043402  2.356578              4.202259
min     0.139000  0.069000   0.139000  0.069000              1.508750
25%     0.263000  0.372000   0.263000  0.372000              2.050250
50%     1.673000  1.612000   1.673000  1.612000              2.329250
75%     2.600000  2.800000   2.600000  2.800000              9.137250
max    34.729000  5.893000  34.729000  5.893000             10.049500

ultima coluna -
                0         1         2          3         4  media_da_media
count   4.000000  4.000000  4.000000   4.000000  4.000000        4.000000
mean   10.049500  2.329250  1.508750   9.137250  2.050250        5.015000
std    16.499883  2.479423  1.378677  17.075994  2.640696        3.309372
min     0.069000  0.139000  0.263000   0.069000  0.263000        2.149000
25%     1.967250  1.243750  0.344750   0.121500  0.344750        2.149000
50%     2.700000  1.642500  1.486000   0.875500  1.022500        5.015000
75%    10.782250  2.728000  2.650000   9.891250  2.728000        7.881000
max    34.729000  5.893000  2.800000  34.729000  5.893000        7.881000