In [4]:
1 == 1

True

In [5]:
2 >= 2

True

In [6]:
1 < 2 < 3

True

In [6]:
import numpy as np  
import pandas as pd

In [ ]:
(1, 2) == (1.0, 2.0)

True

In [11]:
lista_1 = [1, 2, 3]
lista_2 = [1, 2, 3]
lista_1 == lista_2

True

In [6]:
array = np.random.normal(0,1,1_100).reshape(10,-1)
array.shape

(10, 110)

In [5]:
np.random.seed(42)
array_1 = np.random.normal(0,1,1_100).reshape(-1,10)
array_2 = np.random.normal(0,1,1_100).reshape(-1,10)
array_1 == array_2

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(110, 10))

In [8]:
pd.DataFrame(array_1)<=pd.DataFrame(array_2)

         0      1      2      3      4      5      6      7      8      9
0     True  False   True  False   True  False  False  False  False   True
1     True   True   True   True   True   True   True  False   True   True
2    False   True   True   True   True  False   True  False   True   True
3     True  False   True   True  False   True   True   True   True   True
4    False   True  False   True   True   True  False  False   True   True
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
105   True   True  False  False  False   True  False  False   True   True
106  False   True  False   True   True   True   True  False   True   True
107   True  False  False   True  False   True  False   True   True  False
108   True  False   True  False  False   True  False  False  False   True
109  False   True   True  False  False  False   True   True  False   True

[110 rows x 10 columns]

In [9]:
filtro_array = array_1 <= array_2
filtro_array[:2]

array([[ True, False,  True, False,  True, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True]])

In [13]:
df_1 = pd.DataFrame(array_1)
df_2 = pd.DataFrame(array_2)
df_1

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040
...,...,...,...,...,...,...,...,...,...,...
105,-0.625563,0.395804,0.494030,0.260674,-0.550305,-0.671623,-0.025554,1.172729,0.543600,-0.370614
106,0.771699,-2.848543,1.148766,-1.739714,-0.362441,-1.119670,-1.294681,1.160827,-0.467701,0.346504
107,-0.046921,0.477041,0.076822,-1.282992,0.996267,-0.493757,-1.556582,-0.428115,1.500760,0.850222
108,-0.348652,-0.349258,-0.321635,2.076748,0.381935,0.430042,1.030283,0.238789,-0.259042,-0.196350
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488

In [12]:
df_1 [filtro_array]

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
...,...,...,...,...,...,...,...,...,...,...
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488
109,-0.071601,-0.037222,0.727630,0.051946,0.732640,-0.080717,0.078635,-1.998201,0.916328,0.346488